/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yangwentao' at '21-6-25 下午4:37' with Gradle 2.14.1
 *
 * @author yangwentao, @date 21-6-25 下午4:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
